### ISSUE TITLE
Window Focus Lost on Popup/Popunder

### ISSUE THREAD

**Issue by FredTheMole** [philikon/BarTab#62] opened 2010-06-21 14:48 UTC
When a website I'm viewing generates a pop-up / pop-under, the window I was working in loses focus and focus jumps to another Firefox window.

Using BarTab 2.0b5 on Mozilla Firefox 3.6.3

**Comment by philikon** [comment] 2010-07-13 11:08
And this behaviour doesn't happen when you disable BarTab?

Do you have a URL that exhibits this behaviour so I can reproduce it myself?

**Comment by FredTheMole** [comment] 2010-07-13 19:00
I'll try to get as much information as I can next time it happens, though after some more observation I'm thinking it's caused by the window focus being moved when a tab unloads (the window that the unloaded tab is in takes focus)  I've also experienced tab focus shifts within a window (unloaded tab takes focus from active tab)

**Comment by FredTheMole** [comment] 2010-07-13 19:20
I'll try to save as much information as I can next time I experience this.  Though, now I'm pretty sure it was actually caused by tabs being unloaded (window containing unloaded tab steals focus from active window) also happened when tabs in active window were unloaded (focus would leave active tab and switch to parent of unloaded tab (parent in tree style tabs))

**Comment by philikon** [comment] 2010-07-13 20:42
Note that there are sites that produce popups or popunders when you leave them. Closing or unloading a tab constitutes as leaving. So that's really not BarTab's fault (more like Firefox's in general). Please reopen with more info if problem persists. But please test first if the problem is also there with BarTab disabled (because in that case it's not a bug in BarTab).

**Closed as completed by philikon** 2010-07-13 20:42 UTC
Labels: Wont fix
