### ISSUE TITLE
Incompatibility with TabPopup

### ISSUE THREAD

**Issue by qwerty017** [philikon/BarTab#41] opened 2010-05-06 19:02 UTC
Your extension seems to be somewhat incompatible with the extension Tab Popup. Before tabs have loaded Tab Popup shows about:blank as the URL of the tab. I tried another extension similar to yours, "Load tabs progressively", and it is able to show the correct URL of the unloaded tabs. Would it be possible for you to implement whatever fix they used so that Tab Popup shows the unloaded tabs correct URL?

**Comment by philikon** [comment] 2010-05-07 10:32
I agree that this would be nice to have. Technically speaking this is  a dupe of issue #36 (both involve making browser.currentURI work for unloaded tabs). Closing this.

**Comment by qwerty017** [comment] 2010-05-07 14:09
Ah. Cool. Thanks for taking a looking into it on another ticket. :)

**Comment by philikon** [comment] 2010-05-07 14:27
Actually, solving #36 hasn't solved this :(. Just had a closer look at TabPopup, it uses browser.contentWindow.location rather than browser.currentURI. That'll be much harder to fake.

**Comment by qwerty017** [comment] 2010-05-07 14:38
Take a look at Load Tabs Progressively. I don't know how they did it but however they got it to work it works perfectly.

**Comment by philikon** [comment] 2010-05-09 13:02
Use docshell.setCurrentURI() to fake currentURI.  This will make sure that window.location pointed to the right URI as well.

Solves compatibility issues with extensions such as Tab Popup.  Closed by 3c59d6096d6bc3bb120884be98b546934cc1f986.

**Closed as completed by philikon** 2010-05-09 13:02 UTC
Labels: Compatibility
