### ISSUE TITLE
Latest version of BarTab (Beta) creates new tab problems 

### ISSUE THREAD

**Issue by Monotonousblob** [philikon/BarTab#37] opened 2010-04-30 21:11 UTC
When opening a link in a new tab, nothing happens under the latest beta version.

**Comment by philikon** [comment] 2010-04-30 23:46
Thanks for the feedback. To track this down, could you let me know
- which version of Firefox you are using
- which other add-ons you have installed (if any, did you try disabling them?)
- what you have the "When opening tabs in the background" preference set to

Thanks!

**Comment by Monotonousblob** [comment] 2010-04-30 23:50
1.6b1

I have other addon's but I disable the ones that updated at the same time as this and it did nothing

I have it set to open regularly (not put on the tab)

**Comment by philikon** [comment] 2010-04-30 23:53
Thanks. Which version of _Firefox_ are you using, though?

As far as the add-ons are concerned, your "disable the ones that updated at the same time" logic is flawed. Due to under-the-hood changes, BarTab could now be incompatible with an already installed add-on that wasn't updated.

**Comment by Monotonousblob** [comment] 2010-05-01 00:00
Version 3.6.4

The only extension I thought might be a problem was the tab mix plus, so I disabled it, I could open bookmarks in the background then, but I couldn't open links from the sidebar

For the full list, here it is (yes I use a lot of extensions)

Adblock Plus
Adblock Plus: Element Hiding Helper
All-in-One Sidebar
AutoPager
Compact Menu 2
Context Search
Digg Toolbar for Firefox
Download Statusbar
FireShot
Fission
Greasefire
Greasemonkey
Image Zoom
Link Alert
Locationbar²
Nightly Tester Tools
Paste Email Plus
PingFire
Read It Later
SearchPreview
Secure Login
SkipScreen
Socialite
Stay-Open Menu
Stylish
Tab History
Tab Mix Plus
Targeted Advertising Cookie Opt-Out (TACO)
Text Link
TinEye Reverse Image Search
Toolbar Buttons
Ubiquity
Vacuum Places Improved
Weave Sync
Xmarks
OptimizeGoogle
Tab Scope
Siphon - Sync Add-ons
BarTab
4chan
Google Toolbar for Firefox
Better Gmail 2
Google Gears
Java Console
FlashGot

**Comment by philikon** [comment] 2010-05-01 00:13
Thanks. So Tab Mix Plus seems to be the culpritm, yes? I did test BarTab 1.6b1 with TMP, although I did not change any of the TMP settings. It would be great if you could let me know about your TMP-specific tab settings so I could reproduce the issue, e.g. by sending me your prefs.js file (you can find it in the profile directory which is linked from about:support).

**Comment by Monotonousblob** [comment] 2010-05-01 00:27
I don't know haw to send a file through here, so I exported my Tab Mix Plus settings and I'll just paste them below

tabmixplus
browser.link.open_newwindow=3
browser.link.open_external=3
browser.link.open_newwindow.restriction=0
extensions.tabmix.linkTarget=false
extensions.tabmix.enablefiletype=true
extensions.tabmix.speLink=0
extensions.tabmix.singleWindow=false
extensions.tabmix.loadOnNewTab=4
extensions.tabmix.newTabUrl=http://www.google.com/
extensions.tabmix.openNewTabNext=false
extensions.tabmix.openTabNext=true
extensions.tabmix.openTabNextInverse=true
extensions.tabmix.openDuplicateNext=true
extensions.tabmix.opentabfor.bookmarks=false
extensions.tabmix.opentabfor.urlbar=true
browser.tabs.loadFolderAndReplace=false
browser.search.openintab=true
extensions.tabmix.opentabfor.history=true
extensions.tabmix.middlecurrent=false
browser.tabs.loadInBackground=true
extensions.tabmix.loadUrlInBackground=false
browser.tabs.loadDivertedInBackground=false
extensions.tabmix.loadSearchInBackground=false
extensions.tabmix.loadNewInBackground=false
browser.tabs.loadBookmarksInBackground=true
extensions.tabmix.loadDuplicateInBackground=false
extensions.tabmix.loadBookmarksGroupInBackground=false
extensions.tabmix.inversefocusLinks=false
extensions.tabmix.inversefocusOther=false
extensions.tabmix.tabs.warnOnClose=true
browser.tabs.warnOnClose=true
extensions.tabmix.protectedtabs.warnOnClose=true
browser.tabs.closeWindowWithLastTab=true
extensions.tabmix.keepLastTab=false
extensions.tabmix.replaceLastTabWith=0
extensions.tabmix.newTabUrl_afterLastTab=
extensions.tabmix.focusTab=5
extensions.tabmix.mergeAllWindows=true
extensions.tabmix.mergePopups=true
extensions.tabmix.placePopupNextToOpener=true
extensions.tabmix.closeOnSelect=true
extensions.tabmix.warnOnclose=true
extensions.tabmix.undoClose=true
browser.sessionstore.max_tabs_undo=30
extensions.tabmix.undoClosePosition=true
extensions.tabmix.undoCloseButton.menuonly=false
browser.ctrlTab.previews=false
extensions.tabmix.lasttab.tabPreviews=true
extensions.tabmix.lasttab.showTabList=false
extensions.tabmix.lasttab.respondToMouseInTabList=true
extensions.tabmix.disableF8Key=true
extensions.tabmix.slideDelay=10
extensions.tabmix.reloadEvery.onReloadButton=false
extensions.tabmix.newTabButton=false
extensions.tabmix.newTabButton.position=2
extensions.tabmix.hideTabBarButton=true
extensions.tabmix.hideAllTabsButton=true
browser.allTabs.previews=false
extensions.tabmix.tabBarSpace=false
extensions.tabmix.hideTabbar=1
extensions.tabmix.tabBarPosition=0
extensions.tabmix.tabBarMode=2
extensions.tabmix.tabBarMaxRow=10
extensions.tabmix.clickToScroll.scrollDelay=150
extensions.tabmix.currentTab=true
extensions.tabmix.unreadTab=true
extensions.tabmix.otherTab=true
extensions.tabmix.extraIcons=true
extensions.tabmix.progressMeter=true
extensions.tabmix.noprogress=false
extensions.tabmix.tabXMode.enable=true
extensions.tabmix.tabXLeft=false
extensions.tabmix.tabXMode=1
extensions.tabmix.tabXDelay=50
browser.tabs.tabClipWidth=140
browser.tabs.tabMinWidth=100
browser.tabs.tabMaxWidth=250
extensions.tabmix.flexTabs=false
extensions.tabmix.titlefrombookmark=false
extensions.tabmix.mouseOverSelect=false
extensions.tabmix.mouseOverSelectDelay=250
extensions.tabmix.tabFlip=false
extensions.tabmix.tabFlipDelay=250
extensions.tabmix.enableScrollSwitch=false
extensions.tabmix.reversedScroll=false
extensions.tabmix.mouseDownSelect=false
extensions.tabmix.middleclickDelete=true
extensions.tabmix.useFirefoxDragmark=true
extensions.tabmix.dblClickTab=0
extensions.tabmix.dblClickTabbar=1
extensions.tabmix.middleClickTab=2
extensions.tabmix.middleClickTabbar=10
extensions.tabmix.ctrlClickTab=22
extensions.tabmix.ctrlClickTabbar=0
extensions.tabmix.shiftClickTab=5
extensions.tabmix.shiftClickTabbar=0
extensions.tabmix.altClickTab=6
extensions.tabmix.altClickTabbar=0
extensions.tabmix.newTabMenu=true
extensions.tabmix.duplicateMenu=true
extensions.tabmix.duplicateinWinMenu=false
extensions.tabmix.detachTabMenu=false
extensions.tabmix.showMergeWindow=false
extensions.tabmix.renameTabMenu=false
extensions.tabmix.copyTabUrlMenu=true
extensions.tabmix.reloadTabMenu=true
extensions.tabmix.autoReloadMenu=true
extensions.tabmix.reloadAllMenu=true
extensions.tabmix.reloadLeftMenu=false
extensions.tabmix.reloadRightMenu=false
extensions.tabmix.reloadOtherMenu=true
extensions.tabmix.undoCloseTabMenu=true
extensions.tabmix.undoCloseListMenu=true
extensions.tabmix.closeTabMenu=true
extensions.tabmix.closeAllMenu=true
extensions.tabmix.closeSimilarTabs=false
extensions.tabmix.closeOtherMenu=true
extensions.tabmix.closeLeftMenu=true
extensions.tabmix.closeRightMenu=true
extensions.tabmix.docShellMenu=false
extensions.tabmix.freezeTabMenu=false
extensions.tabmix.protectTabMenu=true
extensions.tabmix.lockTabMenu=true
extensions.tabmix.bookmarkTabMenu=true
extensions.tabmix.bookmarkTabsMenu=true
extensions.tabmix.openLinkHere=false
extensions.tabmix.openInverseLink=true
extensions.tabmix.openAllLinks=true
extensions.tabmix.linkWithHistory=false
extensions.tabmix.autoReloadContent=true
extensions.tabmix.closeTabContent=false
extensions.tabmix.duplicateTabContent=false
extensions.tabmix.duplicateWinContent=false
extensions.tabmix.detachTabContent=false
extensions.tabmix.mergeWindowContent=false
extensions.tabmix.freezeTabContent=false
extensions.tabmix.protectTabContent=false
extensions.tabmix.lockTabContent=false
extensions.tabmix.tabsList=false
extensions.tabmix.undoCloseListContent=false
extensions.tabmix.undoCloseTabContent=true
extensions.tabmix.optionsToolMenu=true
extensions.tabmix.sessionToolsMenu=true
extensions.tabmix.closedWinToolsMenu=false
browser.warnOnRestart=false
browser.warnOnQuit=true
browser.startup.page=1
browser.sessionstore.resume_from_crash=true
browser.sessionstore.interval=30000
browser.sessionstore.privacy_level=1
browser.sessionstore.postdata=0
extensions.tabmix.sessions.manager=false
extensions.tabmix.sessions.crashRecovery=false
extensions.tabmix.sessions.onStart=2
extensions.tabmix.sessions.onClose=0
extensions.tabmix.sessions.onStart.loadsession=-1
extensions.tabmix.sessions.onStart.askifempty=true
extensions.tabmix.sessions.restore.overwritewindows=true
extensions.tabmix.sessions.restore.overwritetabs=true
extensions.tabmix.sessions.restore.saveoverwrite=true
extensions.tabmix.sessions.restore.concatenate=false
extensions.tabmix.sessions.restore.reloadall=false
extensions.tabmix.sessions.save.history=true
extensions.tabmix.sessions.save.permissions=true
extensions.tabmix.sessions.save.scrollposition=true
extensions.tabmix.sessions.save.protected=true
extensions.tabmix.sessions.save.locked=true
extensions.tabmix.sessions.save.selectedtab=true
extensions.tabmix.sessions.save.closedtabs=false
extensions.tabmix.sessions.onStart.sessionpath=
extensions.tabmix.unreadTabreload=true
extensions.tabmix.reload_time=300
extensions.tabmix.custom_reload_time=90
extensions.tabmix.filetype=xpi zip rar exe tar jar gzip gz ace bin doc xls mdb ppt iso 7z cab arj lzh uue torrent /&disp=attd&/ php\?attachmentid=.\* php\?act=Attach&type=post&id=.\* /download.(php|asp)\?*/
extensions.tabmix.sessions.menu.showext=true
extensions.tabmix.disableIncompatible=true
extensions.tabmix.hideIcons=false
extensions.tabmix.disableF9Key=true
extensions.tabmix.styles.currentTab=italic:false,bold:true,underline:true,text:true,textColor:'rgba(0,0,0,1)',bg:false,bgColor:'rgba(236,233,216,1)'
extensions.tabmix.styles.unreadTab=italic:true,bold:true,underline:true,text:true,textColor:'rgba(255,255,0,1)',bg:false,bgColor:'rgba(236,233,216,1)'
extensions.tabmix.styles.otherTab=italic:false,bold:true,underline:false,text:true,textColor:'rgba(255,0,0,1)',bg:false,bgColor:'rgba(236,233,216,1)'
extensions.tabmix.styles.progressMeter=bg:true,bgColor:'rgba(170,170,255,1)'

**Comment by philikon** [comment] 2010-05-01 00:30
Cool, I'll take a look and see if I can reproduce the problem.

**Comment by philikon** [comment] 2010-05-02 02:46
Commit a8c0985b6b2811ea9af41723580973a432749514 should fixed the issue. I've just released 1.6b2 containing that fix. Can you try it?

I'm going to close the issue. If for some reason it still doesn't work for you, we can reopen or create a new issue (depending on whether the same problem persists or a new one surfaces).

**Closed as completed by philikon** 2010-05-02 02:46 UTC
Labels: Bug

**Comment by Monotonousblob** [comment] 2010-05-02 03:13
Everything works, you are awesome!

I have a feature request, I'll put it here and if you want I can make it a separate request:

Is it possible to make a list of sites that always load to the tab (such as Youtube to prevent autoplay)

Thanks for the help again!

**Comment by philikon** [comment] 2010-05-02 14:25
Great! As for your feature request, see issue #32.
