### ISSUE TITLE
Clicking link for foreground tab

### ISSUE THREAD

**Issue by qwerty017** [philikon/BarTab#44] opened 2010-05-11 21:43 UTC
Previously in the 1.6 beta when clicking on a link that opens a tab in the foreground it would automatically load as designed. With the latest Beta the following is happening instead.

Go to http://forum.xda-developers.com/showthread.php?p=2718492#post2718492
Left-Click on link under "Solved!".
New tab is automatically loaded.
When clicking on this new tab it removes the URL from the Location Bar and replaces it with about:blank
If I then refresh the page the correct URL is placed back into the Address Bar and stays.

**Comment by philikon** [comment] 2010-05-11 22:07
Are you using an add-on like Tab Mix Plus to modify tab behaviour (e.g. prevent tabs from loading in the foreground?). Because I can't reproduce this bug on a bock standard Firefox instance with BarTab 2.0b2 installed.

**Comment by qwerty017** [comment] 2010-05-11 22:12
No. I just changed browser.tabs.loadDivertedInBackground to "true" in about:config

**Comment by philikon** [comment] 2010-05-11 22:14
Ah yes. Confirmed. Thanks for the report! That definitely has to be fixed.

**Comment by qwerty017** [comment] 2010-05-11 22:15
BTW, I appreciate you looking into these and not getting mad. I had another addon developer do that and it put me off Bug reporting for a while. :)

**Comment by philikon** [comment] 2010-05-12 00:46
So far this is what I've been able to track down:
- window.browserDOMWindow.openURI() (as implemented by nsBrowserAccess) is called with a null URI.
- The caller probably is nsContentTreeOwner::ProvideWindow (https://bugzilla.mozilla.org/show_bug.cgi?id=323810).
- This in turn seems to be called by nsWindowWatcher::OpenWindowJSInternal. It obtains the docshell from the returned window object and then simply does newDocShell->LoadURI(), bypassing BarTab entirely.

We may have go to back to using progress listeners after all...

**Comment by philikon** [comment] 2010-05-12 15:05
Handle tabs that are opened in the background but loaded by C++ code (e.g. when 'browser.tabs.loadDivertedInBackground' is enabled) correctly.

Closed by 45c49e7d43f95238fff72e9a6c4e8e8ca56dfe6f

**Closed as completed by philikon** 2010-05-12 15:05 UTC
Labels: Bug

**Comment by philikon** [comment] 2010-05-12 15:47
Just released 2.0b3 containing that fix. Let me know if you run into any other problems.

**Comment by qwerty017** [comment] 2010-05-12 16:02
Awesome. Absolutely awesome. Works perfectly. Even keeps foreground tabs on the tap now. :)
If I find anything else I will let you know.

**Comment by philikon** [comment] 2010-05-12 16:04
Foreground tabs? How do you mean?

**Comment by qwerty017** [comment] 2010-05-12 17:07
Before in http://github.com/philikon/BarTap/issues/closed#issue/42 you said the reason it was loading was that it was set to open a foreground tab. Now, by setting the about:config entry it is read as a background tab so TabBar puts it on the tap. Exactly as expected since it is now considered a background tab by Firefox.

**Comment by philikon** [comment] 2010-05-12 17:09
Ok!

**Comment by qwerty017** [comment] 2010-05-12 17:11
:)
Man you are fast with the fixes.
